# Generated by Django 5.1.3 on 2025-12-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=64)),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('gender', models.CharField(db_index=True, max_length=16)),
                ('age', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('customer_region', models.CharField(db_index=True, max_length=128)),
                ('customer_type', models.CharField(blank=True, max_length=128)),
                ('product_id', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=128)),
                ('product_category', models.CharField(db_index=True, max_length=128)),
                ('tags', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(db_index=True, max_length=64)),
                ('order_status', models.CharField(blank=True, max_length=64)),
                ('delivery_type', models.CharField(blank=True, max_length=64)),
                ('store_id', models.CharField(db_index=True, max_length=64)),
                ('store_location', models.CharField(db_index=True, max_length=128)),
                ('salesperson_id', models.CharField(blank=True, max_length=64)),
                ('employee_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date', 'id'],
                'indexes': [models.Index(fields=['customer_name'], name='sales_sale_custome_376163_idx'), models.Index(fields=['phone_number'], name='sales_sale_phone_n_ae55ba_idx'), models.Index(fields=['date'], name='sales_sale_date_ca4177_idx'), models.Index(fields=['customer_region', 'product_category'], name='sales_sale_custome_474960_idx')],
            },
        ),
    ]
